### ISSUE TITLE
能加一个orderquery实现吗？

### ISSUE THREAD

**Issue by hanyou** [arccode/wechat-pay-sdk#1]
https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_2&index=4
订单状态查询的接口吗？

**Comment by arccode** [comment]
@hanyou 可以, 今天有点忙, 明天发布

**Comment by arccode** [comment]
发布v1.1.0, 增加查询订单功能

**Comment by hanyou** [comment]
兄弟，你没有测试啊，新包出问题了。
![image](https://user-images.githubusercontent.com/2518751/39197860-31b9f890-4818-11e8-87b2-841cb29a5f27.png)
Error:(67, 16) java: 找不到符号
  符号:   方法 setBody(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(68, 16) java: 找不到符号
  符号:   方法 setDetail(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(69, 16) java: 找不到符号
  符号:   方法 setOutTradeNo(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(70, 16) java: 找不到符号
  符号:   方法 setTotalFee(int)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request

很多方法找不到了

**Comment by arccode** [comment]
发布修复版v1.1.1, 中央库大概1~2天内可用.
