### ISSUE TITLE
1.1.0版本中很多方法找不到了

### ISSUE THREAD

**Issue by hanyou** [arccode/wechat-pay-sdk#2]
Error:(67, 16) java: 找不到符号
  符号:   方法 setBody(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(68, 16) java: 找不到符号
  符号:   方法 setDetail(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(69, 16) java: 找不到符号
  符号:   方法 setOutTradeNo(java.lang.String)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request
Error:(70, 16) java: 找不到符号
  符号:   方法 setTotalFee(int)
  位置: 类型为net.arccode.wechat.pay.api.protocol.unified_order.UnifiedOrderRequest的变量 request

**Comment by hanyou** [comment]
![image](https://user-images.githubusercontent.com/2518751/39221676-f6875f44-486a-11e8-9f74-aa8d6f5636d6.png)

**Comment by arccode** [comment]
v1.1.1已进行修复
